language: php

php:
  - '7.1'

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install:
  - rm composer.lock
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit

jobs:
  include:
    - stage: Code Quality
      script: ./vendor/bin/phpcs --standard=PSR1,PSR2 --extensions=php src/